name: flutter_paystack
description: A Flutter plugin for making payments via Paystack Payment Gateway. Completely supports Android and iOS.
version: 2.0.0
homepage: https://github.com/contactjavas/flutter_paystack

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  intl: ^0.18.1
  meta: ^1.9.1
  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  matcher: ^0.12.15
  mockito: ^5.4.0


flutter:
  plugin:
    platforms:
      android:
        package: co.paystack.flutterpaystack
        pluginClass:  FlutterPaystackPlugin
      ios:
        pluginClass:  FlutterPaystackPlugin

  assets:
   - assets/images/
